name: 'Push Container Image to Docker Hub'
on:
  push:
    branches:
      - master
jobs:
  push-docker-hub:
    name: 'Push to Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
      - name: 'Push to Docker Hub'
        uses: docker/build-push-action@v1
        with:
          dockerfile: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: seesharprun/pandoc-build
          tags: latest
          tag_with_sha: true