name: 'Push Container Image to Docker Hub'
on:
  schedule:
    - cron: '0 1 */15 * *'
  push:
    branches:
      - master
jobs:
  push-docker-hub:
    name: 'Push to Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
      - name: 'Push to Docker Hub'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: seesharprun/pandoc-build
          tags: latest, ${{ github.run_number }}